services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\PayloadSensitizer:
    abstract:  true
    arguments:
      $sensitiveDataManager: '@broadway_sensitive_serializer.data_manager'
      $aggregateKeyManager: '@broadway_sensitive_serializer.aggregate_key_manager'
      $automaticAggregateKeyCreation: '%matiux.broadway.sensitive_serializer.strategy.aggregate_key_auto_creation%'