services:

  broadway_sensitive_serializer.strategy.whole.sensitizer:
    class: Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\WholeStrategy\WholePayloadSensitizer
    parent:   Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\PayloadSensitizer
    arguments:
      $excludedKeys: '%matiux.broadway.sensitive_serializer.strategy.excluded_keys%'
      $excludedIdKey: '%matiux.broadway.sensitive_serializer.strategy.excluded_id_key%'

  broadway_sensitive_serializer.strategy.whole:
    class: Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\WholeStrategy\WholeStrategy
    arguments:
      $wholePayloadSensitizerRegistry: '@broadway_sensitive_serializer.strategy.whole.registry'
      $wholePayloadSensitizer: '@broadway_sensitive_serializer.strategy.whole.sensitizer'