services:

  broadway_sensitive_serializer.strategy.partial.sensitizer:
    class: Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\PartialStrategy\PartialPayloadSensitizer
    parent:   Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\PayloadSensitizer
    arguments:
      $partialPayloadSensitizerRegistry: '@broadway_sensitive_serializer.strategy.partial.registry'

  broadway_sensitive_serializer.strategy.partial:
    class: Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\PartialStrategy\PartialStrategy
    arguments:
      $partialPayloadSensitizerRegistry: '@broadway_sensitive_serializer.strategy.partial.registry'
      $partialPayloadSensitizer: '@broadway_sensitive_serializer.strategy.partial.sensitizer'