services:

  broadway_sensitive_serializer.strategy.partial.sensitizer:
    class: Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\PartialStrategy\PartialPayloadSensitizer
    arguments:
      $sensitiveDataManager: '@broadway_sensitive_serializer.data_manager'
      $aggregateKeyManager: '@broadway_sensitive_serializer.aggregate_key_manager'
      $partialPayloadSensitizerRegistry: '@broadway_sensitive_serializer.strategy.partial.registry'
      $automaticAggregateKeyCreation: '%matiux.broadway.sensitive_serializer.strategy.aggregate_key_auto_creation%'

  broadway_sensitive_serializer.strategy.partial:
    class: Matiux\Broadway\SensitiveSerializer\Serializer\Strategy\PartialStrategy\PartialStrategy
    arguments:
      $partialPayloadSensitizerRegistry: '@broadway_sensitive_serializer.strategy.partial.registry'
      $partialPayloadSensitizer: '@broadway_sensitive_serializer.strategy.partial.sensitizer'