version: '3.9'

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
  id_rsa.pub:
    file: ~/.ssh/id_rsa.pub
  known_hosts:
    file: ~/.ssh/known_hosts

services:

  php_broadway_sensitive_serializer_bundle:
    environment:
      - AGGREGATE_MASTER_KEY="SS3kr3tK31"