name: "Test"

on:
  pull_request: ~
  push: ~
  workflow_dispatch: ~

jobs:

  run-tests:
    name: Run tests
    runs-on: "ubuntu-latest"

    steps:
#      - name: Verify MySQL connection from container
#        run: mysql --host 127.0.0.1 --port 32574 -uroot -proot -e "SHOW DATABASES"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Checkout code
        uses: "actions/checkout@v2"

      - name: Install dependencies
        run: ./tools/bin/project install_dependencies

      - name: Create Schema
        run: ./tools/bin/project schema-create

      - name: "Run unit tests (PHPUnit)"
        env:
          XDEBUG_MODE: coverage

        run: ./tools/bin/project coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./.coverage/coverage-clover.xml